# Deep Learning Lecture 1 : Tensors and Variables

## Do all the necessary imports

In [1]:
import math
import time
import numpy as np
import torch
print(torch.__version__)
print(np.__version__)

2.10.0
2.4.3


## Checking for a GPU

In [2]:
print(torch.version.cuda)
# Check if CUDA (GPU support) is available
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Device name: {torch.cuda.get_device_name(0)}")
else:
    print("GPU is not available.")

None
GPU is not available.


## Creating and viewing a tensor

In [4]:
import numpy as np
import torch
x = torch.tensor([1, 2, 3])
print('Type:', type(x))
print('Shape:', x.shape)
print(x)


Type: <class 'torch.Tensor'>
Shape: torch.Size([3])
tensor([1, 2, 3])


In [5]:
# convert to numpy 
print(x.numpy())
print(type(x.numpy()))

[1 2 3]
<class 'numpy.ndarray'>


## Calculate with Tensors

In [6]:
a = torch.tensor([[1, 2], [3, 4]])                 
b = torch.add(a, 1)

print(type(b))
b.numpy()   

<class 'torch.Tensor'>


array([[2, 3],
       [4, 5]])

In [7]:
# now a float array
c = torch.tensor([[1.0, 2], [3, 4]])
c.device

device(type='cpu')

# Vector math with tensors

In [8]:
n = 10000
a = torch.ones(n)
b = torch.ones(n)
a

tensor([1., 1., 1.,  ..., 1., 1., 1.])

In [9]:
# this will not work, since a tensor by default is not modifyable
a[2]=5.5
a

tensor([1.0000, 1.0000, 5.5000,  ..., 1.0000, 1.0000, 1.0000])

## Unvectorized addition & tensorflow variables

In [10]:
c = torch.zeros(n)
t = time.time()
for i in range(n):
    c[i]=(a[i] + b[i])
f'{time.time() - t:.5f} sec'  # https://realpython.com/python-f-strings/#option-1-formatting 

'0.11115 sec'

Vectorized addition

In [11]:
t = time.time()
d = a + b
f'{time.time() - t:.5f} sec'

'0.00000 sec'

# Comparison with numpy

In [12]:
nn = 100000000
na = np.ones(nn)
nb = np.ones(nn)
t = time.time()
nd = na + nb
f'{time.time() - t:.5f} sec'

'0.27729 sec'

In [13]:
nn = 100000000
na = torch.ones(nn)
nb = torch.ones(nn)
t = time.time()
nd = na + nb
f'{time.time() - t:.5f} sec'

'0.13612 sec'